###Assignment3
version: '3.8'

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge




